#!/usr/bin/env python3
"""Generate security hardening configurations"""
import json
from typing import Dict, List
from pathlib import Path

class SecurityHardening:
    """Generate security fixes and hardening configs"""
    
    def __init__(self, findings: List[Dict]):
        self.findings = findings
        self.fixes = []
    
    def generate_nginx_config(self) -> str:
        """Generate nginx security configuration"""
        config = """# Security Hardening Configuration
# Generated by Cybersecurity Lab

server {
    # Security Headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    
    # Hide server version
    server_tokens off;
    
    # Disable access to hidden files
    location ~ /\\. {
        deny all;
        access_log off;
        log_not_found off;
    }
    
    # Block common attack paths
    location ~ ^/(wp-admin|wp-login\\.php|administrator|admin) {
        deny all;
        return 404;
    }
    
    # Block API documentation in production
    location ~ ^/(openapi\\.json|docs|redoc|swagger) {
        deny all;
        return 404;
    }
    
    # Rate limiting
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
    
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://backend;
    }
    
    # SSL Configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    
    # HSTS (uncomment after confirming HTTPS works)
    # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
}
"""
        return config
    
    def generate_cloudflare_config(self) -> str:
        """Generate Cloudflare security rules"""
        config = """# Cloudflare Security Rules
# Add these in Cloudflare Dashboard > Security > WAF

# 1. Block common attack paths
( http.request.uri.path contains "/.git" or
  http.request.uri.path contains "/.env" or
  http.request.uri.path contains "/wp-admin" or
  http.request.uri.path contains "/wp-login.php" )
=> Action: Block

# 2. Block API documentation
( http.request.uri.path contains "/openapi.json" or
  http.request.uri.path contains "/docs" or
  http.request.uri.path contains "/swagger" )
=> Action: Block

# 3. Rate limit API endpoints
( http.request.uri.path contains "/api/" )
=> Action: Challenge
=> Rate Limit: 10 requests per minute

# 4. Block suspicious user agents
( http.user_agent contains "sqlmap" or
  http.user_agent contains "nikto" or
  http.user_agent contains "nmap" )
=> Action: Block
"""
        return config
    
    def generate_python_fastapi(self) -> str:
        """Generate FastAPI security middleware"""
        code = """# FastAPI Security Middleware
# Add to your main.py

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from fastapi.responses import JSONResponse
import time

app = FastAPI()

# CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://oneresume.life"],  # Replace with your domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Trusted Host Middleware
app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=["oneresume.life", "api.oneresume.life", "*.oneresume.life"]
)

# Security Headers Middleware
@app.middleware("http")
async def add_security_headers(request: Request, call_next):
    response = await call_next(request)
    
    # Add security headers
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-XSS-Protection"] = "1; mode=block"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    response.headers["Permissions-Policy"] = "camera=(), microphone=(), geolocation=()"
    response.headers["Content-Security-Policy"] = "default-src 'self'; script-src 'self'"
    response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
    
    # Remove server header
    if "server" in response.headers:
        del response.headers["server"]
    
    return response

# Rate Limiting Middleware
from collections import defaultdict
import asyncio

request_counts = defaultdict(list)

@app.middleware("http")
async def rate_limit(request: Request, call_next):
    client_ip = request.client.host
    now = time.time()
    
    # Clean old requests
    request_counts[client_ip] = [t for t in request_counts[client_ip] if now - t < 60]
    
    # Check rate limit
    if len(request_counts[client_ip]) > 100:  # 100 requests per minute
        return JSONResponse(
            status_code=429,
            content={"detail": "Too many requests"}
        )
    
    request_counts[client_ip].append(now)
    return await call_next(request)

# Disable OpenAPI in production
@app.get("/openapi.json", include_in_schema=False)
async def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    # Return 404 in production
    from fastapi import HTTPException
    raise HTTPException(status_code=404, detail="Not found")
"""
        return code
    
    def generate_react_security(self) -> str:
        """Generate React security utilities"""
        code = """// React Security Utilities
// Add to your React app

// 1. Secure API calls with CSRF protection
const API_BASE = process.env.REACT_APP_API_URL;

export const secureFetch = async (url: string, options: RequestInit = {}) => {
  const token = localStorage.getItem('auth_token');
  
  const headers = {
    ...options.headers,
    'Content-Type': 'application/json',
    'X-CSRF-Token': getCSRFToken(),
    ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
  };
  
  const response = await fetch(`${API_BASE}${url}`, {
    ...options,
    headers,
    credentials: 'include',
  });
  
  if (!response.ok) {
    throw new Error(`API error: ${response.status}`);
  }
  
  return response.json();
};

// 2. XSS Protection
export const sanitizeInput = (input: string): string => {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#x27;')
    .replace(/\//g, '&#x2F;');
};

// 3. CSRF Token Generation
export const getCSRFToken = (): string => {
  const cookie = document.cookie
    .split(';')
    .find(c => c.trim().startsWith('csrf_token='));
  return cookie ? cookie.split('=')[1] : '';
};

// 4. Secure Storage
export const secureStorage = {
  set: (key: string, value: string) => {
    sessionStorage.setItem(key, value);
  },
  get: (key: string) => {
    return sessionStorage.getItem(key);
  },
  remove: (key: string) => {
    sessionStorage.removeItem(key);
  },
};

// 5. Content Security Policy
export const CSP_NONCE = process.env.REACT_APP_CSP_NONCE;
"""
        return code
    
    def generate_all_fixes(self) -> Dict[str, str]:
        """Generate all fix configurations"""
        return {
            "nginx.conf": self.generate_nginx_config(),
            "cloudflare_rules.txt": self.generate_cloudflare_config(),
            "fastapi_middleware.py": self.generate_python_fastapi(),
            "react_security.js": self.generate_react_security(),
        }
    
    def save_fixes(self, output_dir: str = "hardening"):
        """Save all fixes to files"""
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)
        
        fixes = self.generate_all_fixes()
        
        for filename, content in fixes.items():
            filepath = output_path / filename
            with open(filepath, "w") as f:
                f.write(content)
            print(f"[+] Saved {filepath}")

async def main():
    """Main function"""
    # Example findings
    findings = [
        {"vuln_type": "Missing Content-Security-Policy", "severity": "high"},
        {"vuln_type": "Missing X-Frame-Options", "severity": "medium"},
        {"vuln_type": "Missing HSTS", "severity": "high"},
    ]
    
    hardening = SecurityHardening(findings)
    hardening.save_fixes()
    
    print("\n[*] Generated security hardening configurations")
    print("[*] Files saved to hardening/ directory")

if __name__ == "__main__":
    asyncio.run(main())
